Repository FunnyGuilds/FunnyGuilds, pull requests merged in 2019-08, with the labels that each got.

#1090 GH-1070 Simplify CI builds
  .travis.yml
Labels: Inne

#1099 GH-1098 Release 4.5.1
  README.md
  pom.xml
  src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
  src/main/java/net/dzikoysk/funnyguilds/util/metrics/BStats.java
  src/main/java/net/dzikoysk/funnyguilds/util/metrics/MCStats.java
  updater.txt
Labels: Update

#1105 Fix leader command no guild message
  src/main/java/net/dzikoysk/funnyguilds/command/ExcLeader.java
Labels: Bug
