Repository FunnyGuilds/FunnyGuilds, pull requests merged in 2023-05, with the labels that each got.

#2406 Improve check for uniqueness in scoreboard's update queue (Fix #2405)
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/AbstractScoreboardHandler.java
Labels: Bug, Priority: HIGH

#2419 Fix for guild regions for negative coordinates
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
Labels: Bug, Priority: HIGH

#2427 Fix error in DecentHolograms hook
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/decentholograms/DecentHologramsHook.java
Labels: Error, Priority: HIGH

#2428 Use reposilite jitpack repo
  build.gradle.kts
  plugin/build.gradle.kts
Labels: Dependencies, Priority: HIGH

#2421 Add WorldGuard `friendly-fire` flag
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard6Hook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard7Hook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuardHook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/listener/EntityDamage.java
Labels: Feature

#2423 Cherry-pick `4.x` changes into `5.x`
  build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HeartConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/SecuritySystemConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/decentholograms/DecentHologramsHook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard7Hook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuardHook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/AbstractScoreboardHandler.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/security/SecuritySystem.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/security/SecurityType.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/security/SecurityUtils.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/security/cheat/SecurityFreeCam.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/security/cheat/SecurityReach.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarAttackAsyncTask.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarSystem.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/listener/EntityDamage.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerInteract.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/EntityUtils.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/FunnyBox.java
Labels: Priority: HIGH
