Repository FunnyGuilds/FunnyGuilds, pull requests merged in 2023-03, with the labels that each got.

#2316 Use proper message in /statsreset command
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/MessageConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
Labels: Bug

#2317 GH-2317 Fix searching for NMS class on modern versions
  plugin/src/main/java/net/dzikoysk/funnyguilds/nms/Reflections.java
Labels: Bug, Priority: HIGH

#2318 Correct multi-version tablist support
  nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/ProtocolDependentHelper.java
  nms/v1_10R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_10R1/playerlist/V1_10R1PlayerList.java
  nms/v1_11R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_11R1/playerlist/V1_11R1PlayerList.java
  nms/v1_12R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_12R1/playerlist/V1_12R1PlayerList.java
  nms/v1_13R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_13R2/playerlist/V1_13R2PlayerList.java
  nms/v1_14R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_14R1/playerlist/V1_14R1PlayerList.java
  nms/v1_15R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_15R1/playerlist/V1_15R1PlayerList.java
  nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/playerlist/V1_16R3PlayerList.java
  nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/playerlist/V1_17R1PlayerList.java
  nms/v1_18R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R2/playerlist/V1_18R2PlayerList.java
  nms/v1_19R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R1/playerlist/V1_19R1PlayerList.java
  nms/v1_19R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R2/playerlist/V1_19R2PlayerList.java
  nms/v1_8R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_8R3/playerlist/V1_8R3PlayerList.java
  nms/v1_9R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_9R2/playerlist/V1_9R2PlayerList.java
Labels: Bug, Priority: NORMAL

#2323 Properly relocate YetAnotherMessagesLibrary
  plugin/build.gradle.kts
Labels: Bug

#2330 Fix max enlargement level
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
Labels: Bug, Priority: URGENT

#2325 GH-2315 Release 4.12.0
  .github/README.md
  build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
  plugin/src/main/resources/plugin.yml
  updater-nightly.txt
  updater.txt
Labels: Update

#2335 Hotfix to region deserialization
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
Labels: Bug, Priority: URGENT

#2303 GH-2303 Code cleanup
  plugin/build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/ConfigurationFactory.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/MessageConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/TopConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/placeholderapi/PlaceholderAPIHook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildUtils.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionUtils.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/rank/placeholders/RankPlaceholdersService.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserManager.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserUtils.java
  plugin/src/test/kotlin/net/dzikoysk/funnyguilds/FunnyGuildsSpec.kt
  plugin/src/test/kotlin/net/dzikoysk/funnyguilds/rank/RankPlaceholdersServiceTest.kt
  plugin/src/test/kotlin/net/dzikoysk/funnyguilds/rank/RankUtilsTest.kt
Labels: Cleanup

#2342 GH-2319 GH-2334 GH-2348 Cleanup code after 4.x
  build.gradle.kts
  nms/api/build.gradle.kts
  plugin/build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/Entity.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/ConfigurationFactory.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/FunnyMessageDispatcher.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/MessageConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/MessageService.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/PlayerLocaleProvider.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/UserLocaleProvider.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/M0001_Migrate_old_region_notification_keys.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/M0002_Migrate_old_rank_kill_message.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0001_Fix_freecam_compensation_key_case.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0002_Migrate_old_heart_configuration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0003_Migrate_old_tnt_protection_configuration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0004_Migrate_tablist_into_separate_file.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0005_Fix_heart_configuration_centery_key.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0006_Migrate_old_scoreboard_configuration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0007_Migrate_old_relational_tag_configuration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0008_Migrate_old_heart_center_configuration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0009_Migrate_old_killer_notification_key.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/T0001_Update_player_list_animated.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/T0002_Update_tablist_keys.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HeartConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistPageSerializer.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/serializer/DatabaseGuildSerializer.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatDataModel.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatPatcher.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/seralizer/FlatGuildSerializer.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/MoveCommand.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookManager.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/funnytab/FunnyTabHook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldedit/WorldEdit6Hook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldedit/WorldEdit7Hook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard6Hook.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/protection/ProtectionSystem.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/nametag/IndividualNameTag.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/security/SecuritySystem.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildManager.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/placeholders/GuildPlaceholdersService.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockPlace.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/nms/BlockDataChanger.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/nms/Reflections.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/adventure/ItemComponentHelper.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/FunnyBox.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ItemBuilder.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ItemUtils.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/LocaleHelper.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/MaterialUtils.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserCache.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/user/placeholders/UserPlaceholdersService.java
Labels: Cleanup

#2360 Properly display protection end time
  plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarSystem.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/guild/placeholders/GuildPlaceholders.java
Labels: Bug

#2365 Update `YAML` and `LocaleLib`
  plugin/build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/FunnyMessageDispatcher.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/config/message/MessageService.java
Labels: Bug, Priority: HIGH

#2369 Update `YAML` to 6.4.1 with critical fix for typed replaceables
  plugin/build.gradle.kts
Labels: Error, Priority: HIGH

#2368 Improve region move handling and fix teleportation
  plugin/src/main/java/net/dzikoysk/funnyguilds/event/guild/GuildRegionEnterEvent.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/event/guild/GuildRegionLeaveEvent.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java
  plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserCache.java
Labels: Bug

#2366 Add 1.19.4 support
  .github/README-PL.md
  .github/README.md
  nms/v1_19R3/build.gradle.kts
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/V1_19R3NmsAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/entity/V1_19R3EntityAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/packet/V1_19R3FunnyGuildsInboundChannelHandler.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/packet/V1_19R3FunnyGuildsOutboundChannelHandler.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/packet/V1_19R3PacketAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/playerlist/V1_19R3PlayerList.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/playerlist/V1_19R3PlayerListAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/statistics/V1_19R3StatisticsAccessor.java
  plugin/build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
  settings.gradle.kts
Labels: Feature

#2378 GH-2367 Add 1.19.4 support to 4.x (#2366)
  .github/README.md
  nms/v1_19R3/build.gradle.kts
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/V1_19R3NmsAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/entity/V1_19R3EntityAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/message/V1_19R3MessageAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/packet/V1_19R3FunnyGuildsInboundChannelHandler.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/packet/V1_19R3FunnyGuildsOutboundChannelHandler.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/packet/V1_19R3PacketAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/playerlist/V1_19R3PlayerList.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/playerlist/V1_19R3PlayerListAccessor.java
  nms/v1_19R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R3/statistics/V1_19R3StatisticsAccessor.java
  plugin/build.gradle.kts
  plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
  settings.gradle.kts
Labels: Feature
