Repository FunnyGuilds/FunnyGuilds, pull requests merged in 2025-03, with the labels that each got.

#2616 Preserve plugin jar from workflow
  .github/workflows/gradle.yml
  .github/workflows/publish.yml
  build.gradle.kts
  gradle.properties
  plugin/build.gradle.kts
  settings.gradle.kts
Labels: Enhancement

#2617 1.18.2 should work again
  .github/workflows/gradle.yml
  settings.gradle.kts
Labels: Error

#2619 GH-2619 Fix 1.20 NMS support
  nms/v1_20R1/build.gradle.kts
  nms/v1_20R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_20R1/packet/V1_20R1FunnyGuildsInboundChannelHandler.java
  nms/v1_20R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_20R1/playerlist/V1_20R1PlayerList.java
Labels: Bug
